name: 'Cancel Previous Runs Action'
description: 'Cancels any previous with state `in_progress` or `queued` for the current workflow. Events (merge_group, pull_request, push)'
branding:
  icon: 'alert-octagon'
  color: 'green'
inputs:
  workflow_names:
    description: 'Specifies the list of workflow names to stop the runs'
    type: string
    required: false
  github_token:
    description: 'Your GitHub Token, (Default: {{ github.token }} )'
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
  - name: Cancel
    shell: bash
    run: ${GITHUB_ACTION_PATH}/cancel.sh
    env:
      GH_TOKEN: ${{ inputs.github_token }}
      WORKFLOW_NAMES: ${{ inputs.workflow_names }}