name: 'Cancel Previous Runs Action'
description: 'Cancels any previous runs that are `in_progress` or `queued` state for the current workflow. Supported events: merge_group, pull_request, push'
branding:
  icon: 'alert-octagon'
  color: 'green'
inputs:
  github_token:
    description: 'Your GitHub Token, (Default: {{ github.token }} )'
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
  - name: Cancel
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github_token }}
    run: |
      ./.github/actions/cancel-previous-runs-action/cancel.sh