name: 'Cancel Previous Runs Action'
description: 'Cancels any previous runs that are `in_progress` for a given workflow. (for merge_group event only at the moment)'
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  workflow_names:
    description: 'Specifies the list of workflow names to stop the runs'
    type: string
    required: false
  github_token:
    description: 'Specifies the GitHub Token, (Default: {{ github.token }} )'
    type: string
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
  - name: Cancel
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github_token }}
      WORKFLOW_NAMES: ${{ inputs.workflow_names }}
    run: |
      ./.github/actions/cancel-previous-runs-action/cancel.sh