name: Sleep120

on:
  pull_request:
    branches:
    - main
  merge_group:
    types:
    - checks_requested
    branches:
    - main
  push:
    branches:
    - main

jobs:

  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: pierreraffa/cancel-previous-runs-action

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout
      - run: sleep 180 && echo "Passed"