name: Test

on:
  pull_request:
    branches:
    - main
  merge_group:
    types:
    - checks_requested
    branches:
    - main
  push:
    branches:
    - main

jobs:

  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cancel Previous Runs
        uses: ./.github/actions/cancel-previous-runs-action
        # uses: PierreRAFFA/cancel-previous-runs-action@1.0

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - run: sleep 180 && echo "Passed"